#!/bin/bash
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - #
# @brief  Build and install the coolPropMixture model package.
#
# Uses CASTROSampling: constrained LHS for composition inputs (x_N2, x_O2)
# with Σ xi = 1 enforced by the sequential conditional algorithm.
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - #

MODENA_MODELS=("coolPropMixture")
MODENA_MODELS_DIR="../MoDeNaModels"

BUILD_DIR="${PWD}/build"
INSTALL_DIR="${PWD}/models"

echo "Compiling and Installing ${#MODENA_MODELS[@]} models"

for MODEL in "${MODENA_MODELS[@]}"; do
    cmake -DCMAKE_INSTALL_PREFIX:PATH="${INSTALL_DIR}" \
          -H"${MODENA_MODELS_DIR}/${MODEL}" \
          -B"${BUILD_DIR}/${MODEL}"
    cmake --build "${BUILD_DIR}/${MODEL}"
    cmake --build "${BUILD_DIR}/${MODEL}" --target install
done
