#!/bin/bash
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - #
# @brief  Build and install the coolPropMixtureTP model package.
#
# Uses ExpandedCASTROSampling: T and p sampled via LHS; x_N2 and x_O2
# sampled with CASTRO constrained algorithm; joint distance selection.
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - #

MODENA_MODELS=("coolPropMixtureTP")
MODENA_MODELS_DIR="../MoDeNaModels"

BUILD_DIR="${PWD}/build"
INSTALL_DIR="${PWD}/models"

echo "Compiling and Installing ${#MODENA_MODELS[@]} models"

for MODEL in "${MODENA_MODELS[@]}"; do
    cmake -DCMAKE_INSTALL_PREFIX:PATH="${INSTALL_DIR}" \
          -H"${MODENA_MODELS_DIR}/${MODEL}" \
          -B"${BUILD_DIR}/${MODEL}"
    cmake --build "${BUILD_DIR}/${MODEL}"
    cmake --build "${BUILD_DIR}/${MODEL}" --target install
done
