#!/bin/bash
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - #
# @brief  Build and install the coolProp model package.
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - #

MODENA_MODELS=("coolProp")
MODENA_MODELS_DIR="../MoDeNaModels"

BUILD_DIR="${PWD}/build"
INSTALL_DIR="${PWD}/models"

echo "Compiling and Installing ${#MODENA_MODELS[@]} models"

for MODEL in "${MODENA_MODELS[@]}"; do
    cmake -DCMAKE_INSTALL_PREFIX:PATH="${INSTALL_DIR}" \
          -H"${MODENA_MODELS_DIR}/${MODEL}" \
          -B"${BUILD_DIR}/${MODEL}"
    cmake --build "${BUILD_DIR}/${MODEL}"
    cmake --build "${BUILD_DIR}/${MODEL}" --target install
done
