# Configuration file specifying the models should be searched for locally
[models]
paths = ["./models"]

[surrogate_functions]
lib_dir = "../" # '.' results in function compiled inside launcher_ directory
# lib_dir = "~/.modena/funcs"   # tilde expanded

[simulate]
target = "twoTankMatlab.TwoTankMatlabModel"
